### ISSUE TITLE
Error on getting odds, undefined

### ISSUE THREAD

**Issue by evcoin** [sbefort/pinnacle-sports-api#2]
Using the example given, all other calls work except for odds.

var options = {sportId: 3};
pinnacle.getOdds(options, function(err, response, body) {
  if (err) throw new Error(err);
  console.log(body);
});

returns undefined

**Comment by sbefort** [comment]
Do you know what sport is assigned to ID 3?  It's possible that it's not in season.

**Comment by evcoin** [comment]
confirmed, changing to sports id 4 (basketball) worked. sorry for false error
